### ISSUE TITLE
uninitialized constant Syck::Syck

### ISSUE THREAD

**Issue by aaronjensen** [LRDesign/logical-insight#9]
Seems to be related to delayed_job. One of my projects works fine with rack-bug, same rails version, same ruby version. This one doesn't.

```
NameError: uninitialized constant Syck::Syck
~/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/ext/module.rb:36:in `const_missing'
~/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.0.10/lib/active_support/inflector/methods.rb:124:in `block in constantize'
~/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.0.10/lib/active_support/inflector/methods.rb:123:in `each'
~/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.0.10/lib/active_support/inflector/methods.rb:123:in `constantize'
~/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.0.10/lib/active_support/core_ext/string/inflections.rb:43:in `constantize'
~/.rvm/gems/ruby-1.9.2-p290/gems/delayed_job-2.1.4/lib/delayed/yaml_ext.rb:27:in `yaml_tag_read_class'
~/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/syck.rb:135:in `transfer'
~/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/syck.rb:135:in `node_import'
~/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/syck.rb:135:in `load'
~/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/syck.rb:135:in `load'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:166:in `decode_value'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:170:in `block in retrieve'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:170:in `map'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:170:in `retrieve'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:174:in `for_request'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/database.rb:32:in `retrieve'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/panels/templates_panel.rb:50:in `heading_for_request'
headers_fragment:9:in `block in headers_fragment_locals_panels_request_id'
headers_fragment:5:in `each'
headers_fragment:5:in `headers_fragment_locals_panels_request_id'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/render.rb:20:in `render_template'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/toolbar.rb:50:in `render'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/toolbar.rb:34:in `inject_toolbar'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug/toolbar.rb:20:in `call'
~/.rvm/gems/ruby-1.9.2-p290/bundler/gems/rack-bug-c71e943f153b/lib/rack/bug.rb:55:in `call'
```

**Comment by LRDesign** [comment]
Just clarifying - are you using our fork of rack-bug, or the original?  (Original located at https://github.com/brynary/rack-bug).  Ours has diverged a lot at this point.

You'd be using ours if you installed gem 'lrd_rack_bug', rather than 'rack-bug'.

**Comment by aaronjensen** [comment]
Your fork. I assume that's the best option for rails 3 at the moment?

**Comment by nyarly** [comment]
That's certainly our understanding.

Just looking at the backtrace, I'd say that yes: delayed_job is doing something to YAML support.  I have a vague understanding that Syck may not be the YAML engine in Ruby 1.9, though...  What happens if you open up a "rails console" and serialize something with 

YAML::dump( { "it is now" => Time.now })

**Comment by aaronjensen** [comment]
```
ruby-1.9.2-p290 :002 > yaml = YAML::dump({"it is now" => Time.now})
 => "--- \nit is now: 2011-09-23 07:04:49.031902 -07:00\n" 
ruby-1.9.2-p290 :003 > YAML::load(yaml)
 => {"it is now"=>2011-09-23 07:04:49 -0700} 
```

**Comment by nyarly** [comment]
Okay.  I'll need to try to recreate the issue.  Is there any chance you can share the app code with me - that would help a lot.  Alternatively, maybe just the Gemfile would work?

**Comment by aaronjensen** [comment]
Unfortunately, I can't share the code, but here's the Gemfile & lock w/o rack-bug included. https://gist.github.com/e8d293a261acf48d0e34

**Comment by nyarly** [comment]
Thanks.  I'll see about setting up a test Rails app with something like that Gemset and see if I can replicate the problem.  Looks like if I can get our rack-bug working with all that, we should be able to say something serious about compatibility.

**Comment by aaronjensen** [comment]
Hah, agreed. Lotta gems in that project. Thanks.

**Comment by aaronjensen** [comment]
any luck on this one? was hoping to use rack-bug again today :/

**Comment by LRDesign** [comment]
Hey Aaron, 

We've just released a pretty big new version - no guarantee that it'll fix your issues but it might.  If it doesn't, let us know what happens and we'll see about recreating a dummy project with your Gemfile.
